In [13]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression

In [14]:

df = pd.read_csv('/Users/mac/Desktop/mydata.csv')
df

,date,clock,stadium,class,attendance,Home Team,Goals Home,Away Team,Away Goals,home_possessions,away_possessions,home_shots,away_shots,home_on,away_on,home_off,away_off,home_blocked,away_blocked,home_pass,away_pass,home_chances,away_chances,home_corners,away_corners,home_offside,away_offside,home_tackles,away_tackles,home_duels,away_duels,home_saves,away_saves,home_fouls,away_fouls,home_yellow,away_yellow,home_red,away_red,links
0,28th May 2023,4:30pm,Emirates Stadium,h,"60,095",2,5,13,0,51.0,49.0,14,6,8,0,4,4,2,2,89.0,88.0,3,0,8,4,1,0,82.4,44.4,47.8,52.2,0,3,8,11,0,0,0,0,https://www.skysports.com/football/arsenal-vs-...
1,28th May 2023,4:30pm,Villa Park,h,"42,212",7,2,6,1,40.3,59.7,12,8,5,4,5,3,2,1,75.3,83.6,4,3,4,3,0,6,42.9,15.4,52.2,47.8,3,3,15,16,4,4,0,0,https://www.skysports.com/football/aston-villa...
2,28th May 2023,4:30pm,Gtech Community Stadium,h,"17,120",9,1,1,0,34.4,65.6,11,17,4,3,4,6,3,8,79.3,89.8,2,1,3,4,3,0,64.7,35.7,50.0,50.0,2,3,12,8,4,0,0,0,https://www.skysports.com/football/brentford-v...
3,28th May 2023,4:30pm,Stamford Bridge,d,"40,130",12,1,4,1,64.4,35.6,22,13,5,4,9,5,8,4,88.9,83.3,2,2,10,3,2,1,42.9,42.9,54.5,45.5,3,5,9,11,0,0,0,0,https://www.skysports.com/football/chelsea-vs-...
4,28th May 2023,4:30pm,Selhurst Park,d,"25,198",11,1,16,1,66.0,34.0,15,7,3,4,8,2,4,1,85.7,69.9,1,0,5,4,2,2,40.0,52.6,58.3,41.7,3,2,9,13,0,2,0,0,https://www.skysports.com/football/crystal-pal...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1135,13/09/2020,2:00pm,The Hawthorns,a,0,24,0,18,3,35.8,64.2,7,13,1,7,3,3,3,3,75.9,84.6,0,1,2,5,4,3,71.4,58.8,64.0,36.0,4,1,12,9,1,1,0,0,https://www.skysports.com/football/west-bromwi...
1136,12/9/2020,8:00pm,London Stadium,a,0,14,0,4,2,58.3,41.7,15,15,3,2,5,7,7,6,82.9,77.8,0,1,8,7,2,4,14.3,76.9,40.5,59.5,0,3,13,7,2,2,0,0,https://www.skysports.com/football/west-ham-un...
1137,12/9/2020,5:30pm,Anfield,h,0,5,4,19,3,48.8,51.2,22,6,6,3,3,1,13,2,75.9,75.6,1,0,9,0,2,5,76.9,58.8,53.8,46.2,0,3,9,6,1,0,0,0,https://www.skysports.com/football/liverpool-v...
1138,12/9/2020,3:00pm,Selhurst Park,h,0,11,1,20,0,29.4,70.6,5,9,3,5,2,3,0,1,51.3,79.0,3,2,7,3,4,0,60.0,64.3,50.0,50.0,5,2,14,11,2,1,0,0,https://www.skysports.com/football/crystal-pal...
1139,12/9/2020,12:30pm,Craven Cottage,a,0,10,0,2,3,45.6,54.4,5,13,2,6,2,4,1,3,88.1,89.8,0,1,2,3,2,2,63.6,41.7,53.3,46.7,2,2,12,12,2,2,0,0,https://www.skysports.com/football/fulham-vs-a...

In [15]:
df.isnull().sum()

date                0
clock               0
stadium             0
class               0
attendance          0
Home Team           0
Goals Home          0
Away Team           0
Away Goals          0
home_possessions    0
away_possessions    0
home_shots          0
away_shots          0
home_on             0
away_on             0
home_off            0
away_off            0
home_blocked        0
away_blocked        0
home_pass           0
away_pass           0
home_chances        0
away_chances        0
home_corners        0
away_corners        0
home_offside        0
away_offside        0
home_tackles        0
away_tackles        0
home_duels          0
away_duels          0
home_saves          0
away_saves          0
home_fouls          0
away_fouls          0
home_yellow         0
away_yellow         0
home_red            0
away_red            0
links               0
dtype: int64

In [16]:
# Fix common month typos
df['date'] = df['date'].str.replace(r'st|nd|rd|th', '', regex=True)
df['date'] = df['date'].str.replace(r'Augu', 'August', regex=True)
# Add more replacements if needed, e.g. df['date'] = df['date'].str.replace(r'Janu', 'January', regex=True)
df['date'] = pd.to_datetime(df['date'], format='%d %B %Y', errors='coerce')

In [17]:
df.isnull().sum()

date                390
clock                 0
stadium               0
class                 0
attendance            0
Home Team             0
Goals Home            0
Away Team             0
Away Goals            0
home_possessions      0
away_possessions      0
home_shots            0
away_shots            0
home_on               0
away_on               0
home_off              0
away_off              0
home_blocked          0
away_blocked          0
home_pass             0
away_pass             0
home_chances          0
away_chances          0
home_corners          0
away_corners          0
home_offside          0
away_offside          0
home_tackles          0
away_tackles          0
home_duels            0
away_duels            0
home_saves            0
away_saves            0
home_fouls            0
away_fouls            0
home_yellow           0
away_yellow           0
home_red              0
away_red              0
links                 0
dtype: int64

In [18]:
df.isnull().sum()

date                390
clock                 0
stadium               0
class                 0
attendance            0
Home Team             0
Goals Home            0
Away Team             0
Away Goals            0
home_possessions      0
away_possessions      0
home_shots            0
away_shots            0
home_on               0
away_on               0
home_off              0
away_off              0
home_blocked          0
away_blocked          0
home_pass             0
away_pass             0
home_chances          0
away_chances          0
home_corners          0
away_corners          0
home_offside          0
away_offside          0
home_tackles          0
away_tackles          0
home_duels            0
away_duels            0
home_saves            0
away_saves            0
home_fouls            0
away_fouls            0
home_yellow           0
away_yellow           0
home_red              0
away_red              0
links                 0
dtype: int64

In [19]:
df.drop(['date', 'clock', 'links'], axis=1, inplace=True)

In [20]:
df

,stadium,class,attendance,Home Team,Goals Home,Away Team,Away Goals,home_possessions,away_possessions,home_shots,away_shots,home_on,away_on,home_off,away_off,home_blocked,away_blocked,home_pass,away_pass,home_chances,away_chances,home_corners,away_corners,home_offside,away_offside,home_tackles,away_tackles,home_duels,away_duels,home_saves,away_saves,home_fouls,away_fouls,home_yellow,away_yellow,home_red,away_red
0,Emirates Stadium,h,"60,095",2,5,13,0,51.0,49.0,14,6,8,0,4,4,2,2,89.0,88.0,3,0,8,4,1,0,82.4,44.4,47.8,52.2,0,3,8,11,0,0,0,0
1,Villa Park,h,"42,212",7,2,6,1,40.3,59.7,12,8,5,4,5,3,2,1,75.3,83.6,4,3,4,3,0,6,42.9,15.4,52.2,47.8,3,3,15,16,4,4,0,0
2,Gtech Community Stadium,h,"17,120",9,1,1,0,34.4,65.6,11,17,4,3,4,6,3,8,79.3,89.8,2,1,3,4,3,0,64.7,35.7,50.0,50.0,2,3,12,8,4,0,0,0
3,Stamford Bridge,d,"40,130",12,1,4,1,64.4,35.6,22,13,5,4,9,5,8,4,88.9,83.3,2,2,10,3,2,1,42.9,42.9,54.5,45.5,3,5,9,11,0,0,0,0
4,Selhurst Park,d,"25,198",11,1,16,1,66.0,34.0,15,7,3,4,8,2,4,1,85.7,69.9,1,0,5,4,2,2,40.0,52.6,58.3,41.7,3,2,9,13,0,2,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1135,The Hawthorns,a,0,24,0,18,3,35.8,64.2,7,13,1,7,3,3,3,3,75.9,84.6,0,1,2,5,4,3,71.4,58.8,64.0,36.0,4,1,12,9,1,1,0,0
1136,London Stadium,a,0,14,0,4,2,58.3,41.7,15,15,3,2,5,7,7,6,82.9,77.8,0,1,8,7,2,4,14.3,76.9,40.5,59.5,0,3,13,7,2,2,0,0
1137,Anfield,h,0,5,4,19,3,48.8,51.2,22,6,6,3,3,1,13,2,75.9,75.6,1,0,9,0,2,5,76.9,58.8,53.8,46.2,0,3,9,6,1,0,0,0
1138,Selhurst Park,h,0,11,1,20,0,29.4,70.6,5,9,3,5,2,3,0,1,51.3,79.0,3,2,7,3,4,0,60.0,64.3,50.0,50.0,5,2,14,11,2,1,0,0
1139,Craven Cottage,a,0,10,0,2,3,45.6,54.4,5,13,2,6,2,4,1,3,88.1,89.8,0,1,2,3,2,2,63.6,41.7,53.3,46.7,2,2,12,12,2,2,0,0

In [21]:
df['class'] = df['class'].map({'h':'home_win', 'a':'away_win', 'd':'draw'})

In [22]:
df['attendance'] = df['attendance'].str.replace(',', '').astype(float)
df['attendance'] = df['attendance'].astype(int)

In [23]:
df

,stadium,class,attendance,Home Team,Goals Home,Away Team,Away Goals,home_possessions,away_possessions,home_shots,away_shots,home_on,away_on,home_off,away_off,home_blocked,away_blocked,home_pass,away_pass,home_chances,away_chances,home_corners,away_corners,home_offside,away_offside,home_tackles,away_tackles,home_duels,away_duels,home_saves,away_saves,home_fouls,away_fouls,home_yellow,away_yellow,home_red,away_red
0,Emirates Stadium,home_win,60095,2,5,13,0,51.0,49.0,14,6,8,0,4,4,2,2,89.0,88.0,3,0,8,4,1,0,82.4,44.4,47.8,52.2,0,3,8,11,0,0,0,0
1,Villa Park,home_win,42212,7,2,6,1,40.3,59.7,12,8,5,4,5,3,2,1,75.3,83.6,4,3,4,3,0,6,42.9,15.4,52.2,47.8,3,3,15,16,4,4,0,0
2,Gtech Community Stadium,home_win,17120,9,1,1,0,34.4,65.6,11,17,4,3,4,6,3,8,79.3,89.8,2,1,3,4,3,0,64.7,35.7,50.0,50.0,2,3,12,8,4,0,0,0
3,Stamford Bridge,draw,40130,12,1,4,1,64.4,35.6,22,13,5,4,9,5,8,4,88.9,83.3,2,2,10,3,2,1,42.9,42.9,54.5,45.5,3,5,9,11,0,0,0,0
4,Selhurst Park,draw,25198,11,1,16,1,66.0,34.0,15,7,3,4,8,2,4,1,85.7,69.9,1,0,5,4,2,2,40.0,52.6,58.3,41.7,3,2,9,13,0,2,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1135,The Hawthorns,away_win,0,24,0,18,3,35.8,64.2,7,13,1,7,3,3,3,3,75.9,84.6,0,1,2,5,4,3,71.4,58.8,64.0,36.0,4,1,12,9,1,1,0,0
1136,London Stadium,away_win,0,14,0,4,2,58.3,41.7,15,15,3,2,5,7,7,6,82.9,77.8,0,1,8,7,2,4,14.3,76.9,40.5,59.5,0,3,13,7,2,2,0,0
1137,Anfield,home_win,0,5,4,19,3,48.8,51.2,22,6,6,3,3,1,13,2,75.9,75.6,1,0,9,0,2,5,76.9,58.8,53.8,46.2,0,3,9,6,1,0,0,0
1138,Selhurst Park,home_win,0,11,1,20,0,29.4,70.6,5,9,3,5,2,3,0,1,51.3,79.0,3,2,7,3,4,0,60.0,64.3,50.0,50.0,5,2,14,11,2,1,0,0
1139,Craven Cottage,away_win,0,10,0,2,3,45.6,54.4,5,13,2,6,2,4,1,3,88.1,89.8,0,1,2,3,2,2,63.6,41.7,53.3,46.7,2,2,12,12,2,2,0,0

In [24]:
df['home_possessions'] = df['home_possessions'].astype(int)
df['away_possessions'] = df['away_possessions'].astype(int)

In [25]:
df['home_duels'] = df['home_duels'].astype(int)
df['away_duels'] = df['away_duels'].astype(int)

In [26]:

df.value_counts()

stadium                    class     attendance  Home Team  Goals Home  Away Team  Away Goals  home_possessions  away_possessions  home_shots  away_shots  home_on  away_on  home_off  away_off  home_blocked  away_blocked  home_pass  away_pass  home_chances  away_chances  home_corners  away_corners  home_offside  away_offside  home_tackles  away_tackles  home_duels  away_duels  home_saves  away_saves  home_fouls  away_fouls  home_yellow  away_yellow  home_red  away_red
8 Stadium                  away_win  0           8          0           12         1           42                58                7           18          2        2        5         7         0             9             81.8       88.9       1             2             2             7             0             2             61.5          60.0          42          57          1           2           20          14          2            3            0         0           1
St James' Park, Newcastle  home_win  52268       4          2           3          0           45                54                22          6           6        1        9         3         7             2             77.0       81.1       3             0             7             4             1             0             68.2          66.7          63          36          1           4           8           12          0            0            0         0           1
St. Mary's Stadium         away_win  0           20         1           6          2           59                40                9           8           4        6        1         0         4             2             79.5       67.8       0             2             4             5             1             1             75.0          32.0          45          54          4           3           11          10          0            0            0         0           1
                                                                        2          3           58                42                13          9           5        5        5         4         3             0             85.4       77.3       0             4             4             5             2             2             64.7          53.3          47          52          1           4           11          6           1            2            0         0           1
                                                            0           19         2           51                48                18          15          3        7        11        6         4             2             82.7       74.7       0             1             4             5             2             1             65.2          57.1          38          61          5           3           10          12          0            3            0         0           1
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          ..
Goodison Park              away_win  0           17         1           1          3           29                70                3           16          2        7        1         4         0             5             73.2       90.2       0             1             0             10            0             0             61.1          54.5          53          46          4           1           8           8           2            1            0         0           1
                                                                        3          3           54                45                7           13          1        5        5         5         1             3             84.7       81.5       0             4             5             2             3             1             48.0          30.8          57          42          2           0           12          19          4            2            0         0           1
                                                                        7          2           47                52                16          13          3        5        7         5         6             3             81.9       81.9       2             3             3             6             2             2             65.0          60.0          40          59          3           2           10          13          0            2            0         0           1
                                                                        23         2           65                34                14          14          4        5        5         6         5             3             81.2       68.7       3             0             7             4             2             1             37.5          66.7          50          50          3           3           9           6           0            4            0         0           1
Vitality Stadium           home_win  10536       15         1           5          0           30                69                5           15          2        6        3         8         0             1             65.5       83.4       2             3             3             8             2             4             63.6          68.2          54          45          5           1           7           9           2            1            0         0           1
Name: count, Length: 1140, dtype: int64

In [27]:
df.columns

Index(['stadium', 'class', 'attendance', 'Home Team', 'Goals Home',
       'Away Team', 'Away Goals', 'home_possessions', 'away_possessions',
       'home_shots', 'away_shots', 'home_on', 'away_on', 'home_off',
       'away_off', 'home_blocked', 'away_blocked', 'home_pass', 'away_pass',
       'home_chances', 'away_chances', 'home_corners', 'away_corners',
       'home_offside', 'away_offside', 'home_tackles', 'away_tackles',
       'home_duels', 'away_duels', 'home_saves', 'away_saves', 'home_fouls',
       'away_fouls', 'home_yellow', 'away_yellow', 'home_red', 'away_red'],
      dtype='object')

In [28]:
pd.set_option('display.max_columns', None)

In [29]:
df['home_tackles'] = df['home_tackles'].astype(int)
df['away_tackles'] = df['away_tackles'].astype(int)
df['home_pass'] = df['home_pass'].astype(int)
df['away_pass'] = df['away_pass'].astype(int)

In [30]:
pd.set_option('display.max_rows', None)  # Shows all rows (be careful with large datasets)

In [31]:
df.describe()

,attendance,Home Team,Goals Home,Away Team,Away Goals,home_possessions,away_possessions,home_shots,away_shots,home_on,away_on,home_off,away_off,home_blocked,away_blocked,home_pass,away_pass,home_chances,away_chances,home_corners,away_corners,home_offside,away_offside,home_tackles,away_tackles,home_duels,away_duels,home_saves,away_saves,home_fouls,away_fouls,home_yellow,away_yellow,home_red,away_red
count,1140.000000,1140.000000,1140.000000,1140.000000,1140.000000,1140.000000,1140.000000,1140.000000,1140.000000,1140.000000,1140.000000,1140.000000,1140.000000,1140.000000,1140.000000,1140.000000,1140.000000,1140.000000,1140.000000,1140.000000,1140.000000,1140.000000,1140.000000,1140.000000,1140.000000,1140.000000,1140.000000,1140.000000,1140.000000,1140.000000,1140.000000,1140.000000,1140.000000,1140.000000,1140.000000
mean,26584.311404,11.450000,1.502632,11.450000,1.290351,50.363158,48.758772,13.558772,11.474561,4.715789,4.039474,5.069298,4.232456,3.776316,3.203509,79.264912,78.524561,1.525439,1.321930,5.579825,4.647368,1.700877,1.689474,57.608772,56.499123,50.342982,48.943860,2.728070,3.178070,10.620175,10.567544,1.587719,1.722807,0.051754,0.053509
std,22827.967261,6.815784,1.359450,6.815784,1.233457,12.891785,12.902711,5.615658,5.048515,2.564688,2.359525,2.621838,2.448306,2.562984,2.266833,7.456517,7.342870,1.389242,1.328043,3.055779,2.767909,1.433636,1.496286,12.975479,12.754004,10.761232,10.768879,1.856035,1.978562,3.415676,3.560070,1.216014,1.279406,0.233210,0.236554
min,0.000000,1.000000,0.000000,1.000000,0.000000,17.000000,17.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,49.000000,47.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,12.000000,10.000000,10.000000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,5.750000,0.750000,5.750000,0.000000,40.000000,39.000000,9.000000,8.000000,3.000000,2.000000,3.000000,2.000000,2.000000,1.000000,74.000000,74.000000,0.000000,0.000000,3.000000,3.000000,1.000000,1.000000,50.000000,50.000000,43.000000,42.000000,1.000000,2.000000,8.000000,8.000000,1.000000,1.000000,0.000000,0.000000
50%,29288.500000,11.000000,1.000000,11.000000,1.000000,50.000000,49.000000,13.000000,11.000000,5.000000,4.000000,5.000000,4.000000,3.000000,3.000000,81.000000,80.000000,1.000000,1.000000,5.000000,4.000000,1.000000,1.000000,58.000000,57.000000,50.000000,50.000000,2.000000,3.000000,10.000000,10.000000,1.000000,2.000000,0.000000,0.000000
75%,41889.250000,17.250000,2.000000,17.250000,2.000000,60.000000,59.000000,17.000000,15.000000,6.000000,5.000000,7.000000,6.000000,5.000000,5.000000,85.000000,84.000000,2.000000,2.000000,7.000000,6.000000,2.000000,2.000000,66.000000,66.000000,57.000000,56.000000,4.000000,4.000000,13.000000,13.000000,2.000000,3.000000,0.000000,0.000000
max,75546.000000,25.000000,9.000000,25.000000,7.000000,82.000000,82.000000,33.000000,31.000000,15.000000,14.000000,18.000000,14.000000,14.000000,15.000000,94.000000,94.000000,7.000000,6.000000,17.000000,19.000000,9.000000,10.000000,100.000000,92.000000,90.000000,90.000000,10.000000,11.000000,23.000000,25.000000,6.000000,7.000000,2.000000,2.000000

In [32]:
df.head(10)

,stadium,class,attendance,Home Team,Goals Home,Away Team,Away Goals,home_possessions,away_possessions,home_shots,away_shots,home_on,away_on,home_off,away_off,home_blocked,away_blocked,home_pass,away_pass,home_chances,away_chances,home_corners,away_corners,home_offside,away_offside,home_tackles,away_tackles,home_duels,away_duels,home_saves,away_saves,home_fouls,away_fouls,home_yellow,away_yellow,home_red,away_red
0,Emirates Stadium,home_win,60095,2,5,13,0,51,49,14,6,8,0,4,4,2,2,89,88,3,0,8,4,1,0,82,44,47,52,0,3,8,11,0,0,0,0
1,Villa Park,home_win,42212,7,2,6,1,40,59,12,8,5,4,5,3,2,1,75,83,4,3,4,3,0,6,42,15,52,47,3,3,15,16,4,4,0,0
2,Gtech Community Stadium,home_win,17120,9,1,1,0,34,65,11,17,4,3,4,6,3,8,79,89,2,1,3,4,3,0,64,35,50,50,2,3,12,8,4,0,0,0
3,Stamford Bridge,draw,40130,12,1,4,1,64,35,22,13,5,4,9,5,8,4,88,83,2,2,10,3,2,1,42,42,54,45,3,5,9,11,0,0,0,0
4,Selhurst Park,draw,25198,11,1,16,1,66,34,15,7,3,4,8,2,4,1,85,69,1,0,5,4,2,2,40,52,58,41,3,2,9,13,0,2,0,0
5,Goodison Park,home_win,39201,17,1,15,0,37,62,13,7,6,2,5,3,2,2,73,83,0,0,9,3,0,1,50,58,53,46,1,5,11,12,1,3,0,0
6,Elland Road,away_win,36871,19,1,8,4,52,47,19,11,2,7,7,3,10,1,77,78,1,3,12,3,1,1,54,46,54,45,3,1,8,5,3,0,0,0
7,The King Power Stadium,home_win,32183,18,2,14,1,48,51,13,16,4,3,6,9,3,4,87,88,2,1,3,5,2,3,63,58,68,31,2,2,8,10,1,1,0,0
8,Old Trafford,home_win,32183,3,2,10,1,53,46,21,10,8,3,7,6,6,1,84,84,4,2,5,4,1,1,78,66,46,53,2,6,14,10,1,2,0,0
9,St. Mary's Stadium,draw,31129,20,4,5,4,30,69,15,30,10,8,5,11,0,11,74,86,1,5,2,9,0,0,71,75,54,45,4,6,4,10,0,2,0,0